### ISSUE TITLE
urlextract does not support IP address based URLs

### ISSUE THREAD

**Issue by mikebdotorg** [lipoja/URLExtract#10]
```
$ echo this is a test of http://1.1.1.1/neatstuff using urlextract > urltest
$ echo this is a test of http://fun.domain.com/neatstuff using urlextract >> urltest
$ urlextract urltest
http://fun.domain.com/neatstuff
$
```

URLs containing IPs instead of hostnames are not extracted.

**Comment by mikebdotorg** [comment]
For the moment I made it work by modifying line 99 in urlextract.py to be:

```
            tlds = self._load_cached_tlds()
            tlds.update([ '.'+str(i) for i in range(256) ])
            self._tlds = sorted(tlds, key=len, reverse=True)
```

**Comment by lipoja** [comment]
Yes you are right. The name of tool is misleading. Original purpose of this tool (at least for me) was to extract URLs based on locating TLD in text. It means that extracting URL that does not contain TLD is not yet supported.

I think this is the way in which this tool should improve. 
Thank you for the code above - interesting solution.
I will work on it soon.

**Comment by Lonerider2010** [comment]
As I had the same problems as @mikebdotorg right now, I would like to support his request.
@mikebdotorg: at which line should I insert your code in the current version? Line 99 seems not to be the correct position.
@lipoja: while looking at the code, I found a typo: in line 115 the comment should read:
        # defining default stop chars right

**Comment by mikebdotorg** [comment]
@Lonerider2010 

```    def _reload_tlds_from_file(self):
        """
        Reloads TLDs from file and compile regexp.
        """
        # check if cached file is readable
        if not os.access(self._tld_list_path, os.R_OK):
            print("ERROR: Cached file is not readable for current user. ({})".format(self._tld_list_path))
        else:
            tlds = self._load_cached_tlds()
            tlds.update([ '.'+str(i) for i in range(256) ])
            self._tlds = sorted(tlds, key=len, reverse=True)
            self._tlds_re = re.compile('|'.join([re.escape(str(tld)) for tld in self._tlds]))```

**Comment by Lonerider2010** [comment]
@mikebdotorg: thanks for the complete function. So I changed urlextract.py locally and installed it.
When running the function with a text containing an IP-based URL the following error occurred:
Traceback (most recent call last):
  File "/home/user1/workspace/test/test_url.py", line 112, in <module>
    station_list = read_playlist(tv_playlist)
  File "/home/user1/workspace/test/test_url.py", line 59, in read_playlist
    url = extractor.find_urls(pipe)
  File "/home/user1/workspace/URLExtract/urlextract.py", line 631, in find_urls
    return list(urls)
  File "/home/user1/workspace/URLExtract/urlextract.py", line 614, in gen_urls
    tmp_url = self._complete_url(text, offset + tld_pos, tld)
  File "/home/user1/workspace/URLExtract/urlextract.py", line 449, in _complete_url
    if not self._is_domain_valid(complete_url, tld):
  File "/home/user1/workspace/URLExtract/urlextract.py", line 525, in _is_domain_valid
    host_parts = host.split('.')
AttributeError: 'IPv4Address' object has no attribute 'split'

**Comment by mikebdotorg** [comment]
Sorry @Lonerider2010 - i'm still using a previous version of the code (and uritools) where I don't have this error.  I won't have time to troubleshoot in the near future.

**Comment by lipoja** [comment]
HI, I am working on a fix for this. I am just curios what is your use case? What should be extracted?
Should IP address without schema, port, path, query, etc. be extracted as well? (e.g. 127.0.0.1)

Or should be extracted only IP addresses containing one or more of these parts: schema, port (not sure), path, query, fragment ... for example:

http://127.0.0.1
127.0.0.1/path
127.0.0.1?query
127.0.0.1#fragment

and its combination (e.g. http://127.0.0.1?query)

**Comment by mikebdotorg** [comment]
My use case is extract the entire URL.  Specifically I use it to find URLs inside email and social media to check them for malware.

**Comment by lipoja** [comment]
@infokiller I will extract this request to separate issue. Because `localhost` is not IP address.

**Comment by andreys42** [comment]
is IP address suport permanent or optional at the moment? I need it to be disabled and wonder if it is optional or should be fixed in the source code...

**Comment by lipoja** [comment]
@andreys42 at this moment there is no option or parameter for turning it off and code change is needed for it.
