### ISSUE TITLE
urlextract does not have a stdin option

### ISSUE THREAD

**Issue by mikebdotorg** [lipoja/URLExtract#11]
Most text manipulation tools have the option to work on a file OR from stdin.

stdin is not an option in this tool.

I added a simple CLI option to my version that functioned this way:

```
    if args.input_file:
        with open(args.input_file, "r", encoding="UTF-8") as f:
            content = f.read()

    elif args.stdin:
        content = ' '.join(sys.stdin.readlines())

    for url in urlextract.find_urls(content, args.unique):
        print(url)
```

**Comment by lipoja** [comment]
OK, thank you for this input. I will try implement it in next release.

**Comment by lipoja** [comment]
Support of sys.stdin as input was added. And will be in version 0.8
