### ISSUE TITLE
add types to urlextract

### ISSUE THREAD

**Issue by georgettica** [lipoja/URLExtract#113]
I tried on my repo to run `mypy file.py`
https://github.com/python/mypy
```
 error: Skipping analyzing "urlextract": module is installed, but missing library stubs or py.typed marker
 note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```

**Comment by lipoja** [comment]
Hello,
that is because `urlextract` does not support type checking yet.
I am planning to do it, but it is not on high priority list. _# PRs are welcome ;)._

**Comment by georgettica** [comment]
I'll see how I can learn and contribute.

If you get there before me please note it in this issue?

Thanks in advance and thanks for the warm response :)

**Comment by lipoja** [comment]
I appreciate any contribution and also reporting any issue. 
It keeps me improving this library. And I am glad that there are people using it and also contributing and improving the code. 

Let's agree that any of us will write a comment here once we start implementing type hints (mypy support). 

Thank you!
