### ISSUE TITLE
Wrong indices with uppercase characters in domain name

### ISSUE THREAD

**Issue by tkrissuu** [lipoja/URLExtract#117]
I am getting wrong indices when the domain name of a URL contains uppercase characters.

To reproduce:
```
from urlextract import URLExtract
extractor = URLExtract()
urls = extractor.find_urls("www.Google.com", get_indices=True)
print(urls[0])
urls = extractor.find_urls("www.google.com", get_indices=True)
print(urls[0])
```
Output is:
```
('www.Google.com', (1, 15))
('www.google.com', (0, 14))
```

**Comment by elliotwutingfeng** [comment]
While URI paths can have uppercase characters, [URI schemes are always lowercase](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax). I think the problem has to do with the regex expression found in [gen_urls()](https://github.com/lipoja/URLExtract/blob/638c0e2d4d8fec077b13b0eefb2c96ffaee112be/urlextract/urlextract_core.py#L733)
