### ISSUE TITLE
urlextract returns urls starting with [

### ISSUE THREAD

**Issue by de-odex** [lipoja/URLExtract#12]
![pycharm64_2018-april-06_17 00 54](https://user-images.githubusercontent.com/11498305/38412497-140ca938-39bc-11e8-9449-39a6c3c0ab7d.png)

See image. The url returned contains a [ at the start. I do not know what other information I should add

**Comment by lipoja** [comment]
Hi,
thank you for reporting this issue. I've added '[' to the list of left stop characters. 

But you can set this stop characters to fit your needs by using two methods:
`get_stop_chars_left` and `set_stop_chars_left`

Just have a look to documentation:
https://urlextract.readthedocs.io/en/latest/urlextract.html

```python
from urlextract import URLExtract

extractor = URLExtract()
stop_chars = extractor.get_stop_chars_left() | {'['}  # adding '[' as a stop character
extractor.set_stop_chars_left(stop_chars)

urls = extractor.find_urls("Bla bla 1234[http://www.google.com", True)
print(urls) # prints: ['http://www.google.com']
```
