### ISSUE TITLE
ERROR: Can not download list of TLDs. (URLError: [Errno 104] Connection reset by peer)

### ISSUE THREAD

**Issue by koliaok** [lipoja/URLExtract#130]
code under: 
```
from urlextract import URLExtract

extractor = URLExtract()
extractor.update_when_older(7)
urls = extractor.find_urls("Text with URLs. Let's have URL janlipovsky.cz as an example.")
```
Library version: urlextract==1.6.0

**Comment by lipoja** [comment]
Hello @koliaok, I would need more information:
Where are you running the code? 
Is the user who is running it able to write to `/tmp`?

**Comment by lipoja** [comment]
Closing issue. Lack of information to reproduce it.
