### ISSUE TITLE
Bug with flag `allow_mixed_case_hostname=False`

### ISSUE THREAD

**Issue by GokulNC** [lipoja/URLExtract#151]
Thanks for this great library!

Example issue:
```py
>>> import urlextract
>>> url_extractor = urlextract.URLExtract()
>>> url_extractor.allow_mixed_case_hostname = False
>>> url_extractor.find_urls("main_data_site.group.popular_data_desc")
['main_data_site.group.popular_data_desc']
>>> url_extractor.allow_mixed_case_hostname = True
>>> url_extractor.find_urls("main_data_site.group.popular_data_desc")
[]
```

Why is there such false-positives with `allow_mixed_case_hostname=False` ? @lipoja

**Comment by GokulNC** [comment]
Found even more worse false-positive: @lipoja 
```py
>>> url_extractor.allow_mixed_case_hostname = False
>>> url_extractor.find_urls("144.2 MB")
['144.2']
```

**Comment by lipoja** [comment]
@GokulNC Thank you for reporting it. If you have time for PR that would be nice and welcome. 
Otherwise I would like to ask you to keep reporting broken thing and wait a little bit for a fix from my side. 
I do not have much free time right now. My guess is that I can take a look in a month :(

**Comment by GokulNC** [comment]
No problem, thanks :)

**Comment by lipoja** [comment]
Should be fixed in next release
