### ISSUE TITLE
[Bug] If an url contains an url...

### ISSUE THREAD

**Issue by fabianskii** [lipoja/URLExtract#17]
Hi!

While using the find_urls method I noticed the following:

> https://bladomain.com/bla/?cid=74530889&h=bladomain.com

leads to

`extractor.find_urls("https://bladomain.com/bla/?cid=74530889&h=bladomain.com")`

`['https://bladomain.com/bla/?cid=74530889&h=bladomain.com', 'https://bladomain.com/bla/?cid=74530889&h=bladomain.com']`

is that supposed to happen? :)

**Comment by impredicative** [comment]
It should IMHO ideally return the bigger URL only.

**Comment by lipoja** [comment]
Yes, I agree with you. It should return the longer URL.

**Comment by lipoja** [comment]
This issue should be fixed. The longest URL containing all other URLs is returned.

**Comment by impredicative** [comment]
That's great. Looking forward to a merge into `master` and a new release.
