### ISSUE TITLE
Add ability to read local TLDs file rather than download

### ISSUE THREAD

**Issue by psweetma** [lipoja/URLExtract#18]
Hi.  Thanks for creating URLExtract.  It works well for me locally, but when I deploy a Flask app that uses URLExtract to AWS ElasticBeanstalk (kind of like a PaaS), I get an error.

The problem is that AWS ElasticBeanstalk implements good web server security practices, which includes making the home directory, and the deployed code's directory, read-only.  They will have done this to make it harder for a web app vulnerability to results in a file being written to disk on the web server.

However, this presents a problem for URLExtract - if it's unable to write to the module's `__file__ ` or `$HOME` then it throws an exception because it has nowhere to store the TLDs file.

To get around this, it'd be great if there was the option to be able package the TLDs file as part of the deployed app, and pass the full path to this file to URLExtract at initialisation.  If passed a file path like this URLExtract would use the file, and not try to download a version from iana.org.

This approach also has the added benefit of being more robust - your app is not dependent on being able to download a file from iana.org to work.  It also allows you to guarantee two environments are exactly the same - they will have the same TLDs file (great for testing).  It's also more secure - pulling down files from third-party sites at runtime is considered risky by some, in fact in some commercial environments this is simply not possible - production outbound internet access is blocked for security reasons.

**Comment by lipoja** [comment]
Hi,
thank you for describing this use case. I agree with you in some points. For example my use case was to have always up to date list of TLDs. That is why I wanted to download the file and not keeping it in repository. 

But I think It is good idea, especially for the testing purposes. I will think about it and do it in some way.

**Comment by impredicative** [comment]
I think it's saner for the package to include in it a copy of the file. If the file is very large, it can be stored compressed. It's not a bad idea to just update the package on PyPI every once in a while with the new file.

**Comment by impredicative** [comment]
Think about the use of the package in a serverless setting where instances can be torn down and recreated on demand from scratch. We wouldn't want the file to be downloaded over and over again for no reason, would be. Similarly, think of build bots that rebuild after each commit.

**Comment by lipoja** [comment]
Thanks for the suggestion, I've added list of TLDs to the package.

**Comment by LaundroMat** [comment]
It's late, so my apologies if I'm overlooking something, but would it be an idea to add a parameter to URLExtract() to make it so it does not need a writeable cache directory?

I'm using URLExtract in an AWS Lambda function and I'm pointing URLExtract to the cache directory:

    URLExtract(cache_dir=Path(f'{os.getenv("LAMBDA_TASK_ROOT")}/urlextract/data'))

which generates an error:
> CacheFileError: Cache directory /var/task/urlextract/data is not writable.

The error is caused by https://github.com/lipoja/URLExtract/blob/638c0e2d4d8fec077b13b0eefb2c96ffaee112be/urlextract/cachefile.py#L141
