### ISSUE TITLE
[request] URLExtract.has_url

### ISSUE THREAD

**Issue by impredicative** [lipoja/URLExtract#2]
Thanks for the package. I was very happy to find it. For runtime efficiency, I would like to request a `has_url(text)` method. The point is that in this use case, I only need to know if there is at least one URL in the input string, and so I want a boolean value returned. I am currently using `find_urls(text)` and this works, but this is obviously less efficient in the case of a large input string.

**Comment by lipoja** [comment]
Thank you for using this package. I will try add this feature: detect if the text contains at least one URL as fast as possible. I would like to ask you if you could test it before it goes to master branch. I will tell you when the code is ready. Thank you.

**Comment by lipoja** [comment]
Could you please check ``devel`` branch. There is implemented ``has_urls(text)`` method. I've test it and it works for me, but I would be glad if you could test it on your data too. 

Is speed necessary for you? I am thinking about speeding up few things by rewriting it to Cython.
Thank you.

**Comment by impredicative** [comment]
Speed is not that necessary for me at this time. Thank you for the great offer, however. I actually recommend against rewriting it in Cython if there isn't a strong need, as it may become more difficult to maintain.

I'm quite concerned about the use of `self._break_after_first`. This will break threaded code, and I therefore recommend against it. In fact, if there is any other use of similar instance variables that'll break threaded code, I recommend against it as well. After all, it cannot be assumed that a unique instance of the class will be used in each thread.

I'm actually nervous about modifying `find_urls` to support `has_urls`. I suspect it would be better to copy the part of the `find_urls` that are minimally necessary and use it to implement `has_urls`. IMO, it's okay if some logic is duplicated once.

**Comment by lipoja** [comment]
OK. I will change ``find_urls`` back and maybe duplicate the code. 

Your use case is that you have one object in main thread and then you are calling ``find_urls`` form another threads?

I will think about this use case and try to write it thread safe. 
Thank you for your comments, I really appreciate it.

**Comment by impredicative** [comment]
In general, I think it helps to keep the code relatively thread safe, especially when this can be automatically made possible.

Hypothetically, instead of using `self._break_after_first`, the signature of the `find_urls` method can be modified to include an optional parameter with a default value, i.e. `break_after_first=False`, and this too would address the issue. (I'm not requesting this; I'm just suggesting it as a thread-safe alternative.)

**Comment by lipoja** [comment]
Thank you, good ideas. 
I've created ``gen_urls()`` which returns generator (iterator) over URLs as you suggested. It might cover your needs and looks like better solution than original ``has_urls()`` (which I removed because it seams to be not necessary).

Please check, the devel branch again.

Thank you.

**Comment by impredicative** [comment]
The line `urls = [url for url in self.gen_urls(text)]` can be simplified to `urls = list(self.gen_urls(text))`.

**Comment by lipoja** [comment]
I think it should be everything that you asked for and suggested in devel branch. If its ok for you like that I will move it to master and upload to pipy.
Thank you.

**Comment by impredicative** [comment]
I'm reviewing the diff against master, and I see one minor issue. In `docs/index.rst`, "form given" should be "from given".

**Comment by lipoja** [comment]
Oh no, typo... :] - fixed.
Thank you for consulting and suggesting this feature. I am glad that you are using it and if you want any other feature just open an issue. 

_All discussed features are released in version 0.4._

**Comment by impredicative** [comment]
Works well :+1:
