### ISSUE TITLE
URLExtract installs module "version" out of "urlextract" namespace

### ISSUE THREAD

**Issue by MartinBasti** [lipoja/URLExtract#20]
URLExctract installs `version.py` as a separate module out of `urlextract` namespace.
```
$ pip3 install urlextract
$ python3
>>> import version
>>> version
<module 'version' from '/tmp/venv/lib/python3.6/site-packages/version.py'>
```
This is quite unexpected, PIP packages should use namespaces to avoid mixing with other projects. Currently it has conflict with namespace of https://pypi.org/project/version/ project.

Expected is having at least:
```
>>> from urlexctract import version
```
or better
```
>>> import urlextract
>>> urlextract.__version__
```

**Comment by lipoja** [comment]
Thank you for pointing this out. I've returned version numbering back to manual approach for now.
