### ISSUE TITLE
URL surrounded with parenthesis 

### ISSUE THREAD

**Issue by mehrant95** [lipoja/URLExtract#23]
Hi there, 
I simply tested code below and but surprisingly it returned an empty list:
``` python
from urlextract import URLExtract
extractor = URLExtract()
urls = extractor.find_urls("Let's have URL (stackoverflow.com) as an example.")
print(urls)
```

**Comment by akshitSinghal1989** [comment]
Yes, I too observed the same. And the reason being "enclosures are not in the list of valid tld_after characters". If you have path/query after host (as '/' or '?' are allowed after TLD), it works well. e.g. "(stackoverflow.com\myaccount)"

**Comment by mehrant95** [comment]
Any idea how it can be solved?

**Comment by akshitSinghal1989** [comment]
Simply adding these enclosure characters to the list of allowed tld_after_chars should work as per the logic. But I haven't tested in code. As per logic enclosures are removed from the uri in the last. I have doubt on situations like "stackoverflow.com)" will be handled or not in this.

**Comment by lipoja** [comment]
Hi, could you please check if code in devel branch is behaving as you need? And does not break anything else ;-)

**Comment by aeevrubin** [comment]
Hi, I have the same issue, except there is no text that I have used that will cause URLExtract to output a URL including the example in your documentation...

>>> URLExtract().find_urls("blah excite.com")
[]
>>> URLExtract().find_urls("blah www.excite.com")
[]
>>> from urlextract import URLExtract
>>> 
>>> extractor = URLExtract()
>>> urls = extractor.find_urls("Text with URLs. Let's have URL janlipovsky.cz as an example.")
>>> print(urls) # prints: ['janlipovsky.cz']
[]
>>>

**Comment by lipoja** [comment]
It works for me. Closing issue.
