### ISSUE TITLE
[Question] Force urlextract to use proxy

### ISSUE THREAD

**Issue by adamtimmins** [lipoja/URLExtract#27]
I'm using urlextract in Jupyter where my scripts has set a custom proxy for connecting to the internet. Setting the proxy up for the requests package is fine by just adding the following: 

![image](https://user-images.githubusercontent.com/18688989/47210519-0d308a80-d38b-11e8-9cf9-246f8979127d.png)

Is there anything similar to this in urlextract? Cause right now, when it attempts to download the TLD's it spits an error out saying it can't connect, subsequently running the examples returns the following.

![image](https://user-images.githubusercontent.com/18688989/47210698-816b2e00-d38b-11e8-9b4f-eaf86ca08911.png)

Cheers for any help!

**Comment by Adamtimtim** [comment]
UPDATE: I used a connection without the proxy and still couldn't manage to get the examples to work. So  I deleted the the file .urlextract_tlds

![image](https://user-images.githubusercontent.com/18688989/47216997-c64c9000-d39e-11e8-8862-a09114cbaa23.png)

Re-ran the example, which it downloaded the TLD's. So now the example is working. 

However, I still want to know how I can use the package with a proxy connection without editing the extracturls.py. 

Cheers 👍

**Comment by lipoja** [comment]
Hi, there is no way how to specify proxy for the URLExtract class for now. However Today's release contains already downloaded list of TLDs. So you might not need it with latest version.

**Comment by lipoja** [comment]
@adamtimmins Is a solution that package contains TLDs sufficient (no need to connect to internet) or would you like me to consider the proxy settings?

**Comment by lipoja** [comment]
Closing this issue because urlextract is shipped with downloaded TLDs. Re-open this issue if needed.
