### ISSUE TITLE
Release New Version to PyPi

### ISSUE THREAD

**Issue by CLiu13** [lipoja/URLExtract#29]
In light of the latest changes made to this project, would it be possible to release a new version of URLExtract to PyPi? The most recent release on PyPi was on February 24, while there have been several changes made since then.

**Comment by lipoja** [comment]
wow is it really that long. OK I will have to do something about it. Sorry for not being here because of lack of free time. I will do something about the release.

**Comment by impredicative** [comment]
@lipoja I'm looking to use this package for a serious new project, so I eagerly hope it can be published to PyPI.

Before you publish, however, please test under Python 3.7 and consider formally noting it in `setup.py`.

Please also set `long_description_content_type` to `text/x-rst` as is documented [here](https://packaging.python.org/guides/making-a-pypi-friendly-readme/?highlight=long_description_content_type#including-your-readme-in-your-package-s-metadata).

Thanks very much for your continued efforts.

**Comment by lipoja** [comment]
Hi @impredicative I've made some progress this week so I released new version on pipy. Thank you for the hint with ``long_description_content_type``.

---

And I would like to thank to all the people using urlextract, reporting issues, giving me suggestions how to move with this project! I really appreciate it! Thanks.
