### ISSUE TITLE
More efficient use of memory

### ISSUE THREAD

**Issue by impredicative** [lipoja/URLExtract#3]
urls = list(self.gen_urls(text))
        return urls if not only_unique else list(set(urls))

The above has an issue in that it needlessly creates the initial list even when a set is desired. This can be wasteful of memory. I didn't realize this before, but a better form is:

        urls = self.gen_urls(text)
        urls = set(urls) if only_unique else urls
        return list(urls)

The above form prevents creating a list of possibly non-unique URLs if only the unique ones are desired.

**Comment by lipoja** [comment]
Thank you, I fixed it in minor version 0.4.1
