### ISSUE TITLE
Guarantee order of returned URLs

### ISSUE THREAD

**Issue by impredicative** [lipoja/URLExtract#31]
As a user, I find it important that URLs are always returned in the order they exist (or exist first) in the input text.

Using `set()` unfortunately violates this requirement.

https://github.com/lipoja/URLExtract/blob/5bb2f3792ba9a0ea76777f95f6623534bdbe51b1/urlextract/urlextract_core.py#L755

```python
>>> url_extractor.find_urls('yahoo.com msn.com', only_unique=False)
['yahoo.com', 'msn.com']  # in order
>>> url_extractor.find_urls('yahoo.com msn.com', only_unique=True)
['msn.com', 'yahoo.com']  # NOT IN ORDER!
```
[This thread](https://stackoverflow.com/questions/480214/how-do-you-remove-duplicates-from-a-list-whilst-preserving-order) covers many alternatives. Please consider one of these options. For example, per [this answer](https://stackoverflow.com/a/39835527/) the implementation of `find_urls` could then become:

```python
urls = self.gen_urls(text)
urls = OrderedDict.fromkeys(urls) if only_unique else urls
return list(urls)
```
Adding several unit tests to always ensure the ordering would also be meaningful. Thanks.

**Comment by impredicative** [comment]
@lipoja I hope you can continue to enhance the package. I'm now using it in a [bot](https://github.com/impredicative/irc-url-title-bot) that I built. The bot is live and is relevant to hundreds of users. Thanks.

**Comment by lipoja** [comment]
Thank you for reporting the issue. I am really glad that this package finds its users. I will do my best for enhancing it. Unfortunately I am in the middle of changing jobs, so I am lack of free time (for now). But I will do my best.

Or if there is somebody who wants to help with this package - he/she is more than welcome!

**Comment by lipoja** [comment]
Again BIG thanks for reporting the issue and also for such a exclusive description with a solution! It should be ready on github (for now). I will make release with some other features (when they are ready) as well.
