### ISSUE TITLE
Trailing enclosure characters not always excluded

### ISSUE THREAD

**Issue by jonasengelmann** [lipoja/URLExtract#38]
I have a case where a trailing character is not excluded like expected:

`extractor.find_urls(r"{\url{http://www.google.com}}")`
returns `['http://www.google.com']`

`extractor.find_urls(r"{\url{http://www.google.com/file.pdf}}")`
returns `['http://www.google.com/file.pdf}']`

I am running version 0.10.

**Comment by lipoja** [comment]
Thanks for reporting this issue. 
I fixed parsing of this for case. If you find another wrong behavior or if you need new feature feel free to create another issue.

Thank you!
