### ISSUE TITLE
Leading chars not excluded

### ISSUE THREAD

**Issue by bruno-t-de-renzo** [lipoja/URLExtract#4]
When you have leading chars to the URL, this is not excluded. E.g. "Bla bla 1234|http://www.google.com"

**Comment by lipoja** [comment]
If there is any new character that should be considered as stop character (URL starts or ends with it) it can be set by you via: ``get_stop_chars()`` and ``set_stop_chars()``. 

Example: 
```python
from urlextract import URLExtract

extractor = URLExtract()
stop_chars = extractor.get_stop_chars() + ['|']  # adding '|' as a stop character
extractor.set_stop_chars(stop_chars)

urls = extractor.find_urls("Bla bla 1234|http://www.google.com", True)
print(urls) # prints: ['http://www.google.com']
```

Thank you, I will consider to add '|' as default stop character in new release.

**Comment by bruno-t-de-renzo** [comment]
Thanks!
