### ISSUE TITLE
Support of detecting localhost URLs

### ISSUE THREAD

**Issue by lipoja** [lipoja/URLExtract#45]
@lipoja it would also be great if `http://localhost` can be detected

_Originally posted by @infokiller in https://github.com/lipoja/URLExtract/issues/10#issuecomment-546358120_

**Comment by dmascialino** [comment]
I added this feature in #59 .

**Comment by lipoja** [comment]
@dmascialino Thanks for your time and the patch. 

Could you help me answer this question: 
Should we extract word `localhost` when it is in text alone? 

My thoughts are when you want to try extract something from text about computers and networks you will have lot of `localhost` words in text.

Would not be more better to extract URL with localhost when there is more than just a `localhost`? For example:
`http://localhost`
`localhost/test.html`
`localhost:8080`

and ignore standalone `localhost` words.

**Comment by dmascialino** [comment]
Good question, I found a similar issue reading links from documentation like https://socket.io/docs/ , where `socket.io` appears a lot of times but not with an URL meaning.

I think it's ok to return `localhost` as an URL and let the user decide if it's useful.
