### ISSUE TITLE
URL not extracted if `.` at end of url

### ISSUE THREAD

**Issue by birdsarah** [lipoja/URLExtract#5]
Hi! Thanks for an amazing library. I've successfully used it to extract urls from 2400 documents. But there are just a few, where extraction isn't happening. 

The following content is similar to many other documents that I've extracted from which is why I was surprised it wasn't working.

Here are some example docs:

https://www.sec.gov/Archives/edgar/data/1636023/000117184317003392/0001171843-17-003392.txt
https://www.sec.gov/Archives/edgar/data/1636023/000117184317003392/exh_101.htm
https://www.sec.gov/Archives/edgar/data/1636023/000117184317003392/fsd_053117.htm

Each of the above docs contains the url `www.westrock.com`

I finally figured it out that a period at the end of the url was causing it to not be detected.
I tried futzing with `set_after_tld_chars` and `set_stop_chars` but didn't get anywhere.

I used `content.replace('.com.', '.com')` as a pre-processing workaround (but obviously this isn't particularly scalable as there are lots of other domain extensions)

Thanks again for an amazing library.

**Comment by lipoja** [comment]
Hi, thank you for reporting this issue. I will have a look on it.

**Comment by lipoja** [comment]
Hi Sarah, I am sorry for the delay. This issue should be fixed in version 0.5. Could you please try it out. Thank you and have a nice day!
