### ISSUE TITLE
[Bug] Wrong with url endswith tld

### ISSUE THREAD

**Issue by Phantomdft** [lipoja/URLExtract#52]
for example: http://107.174.47.156/mr.sh ( The url is malicious，be careful).
This url will be  considered  as a url with domain,but  in urlextract_core.py line 530, the host is ipv4, and 'IPv4Address' object has no attribute 'split',will raise the exception.

**Comment by Phantomdft** [comment]
oh, I see. there is another bug  lead to this happen.
In urlextract_core.py line 636: self._tlds_re.findall(text)  when the tld was be matched ,the tld will be .1(It should be .174)
The most convenient way i found is to reverse the _ipv4_tld list :
In urlextract_core.py line 65: 
    before: _ipv4_tld = ['.{}'.format(ip) for ip in range(256)] 
    _ipv4_tld = ['.{}'.format(ip) for ip in range(255,-1,-1)]

**Comment by lipoja** [comment]
Thank you for your time, reporting and also suggesting the patch. 
It will be fixed in next release (probably tomorrow).
