### ISSUE TITLE
'IPv4Address' object has no attribute 'split' v 0.14

### ISSUE THREAD

**Issue by larryrodrigues** [lipoja/URLExtract#57]
If the tld has a value, then the line 524 test returns false.

**Comment by lipoja** [comment]
Thanks for reporting! I have just one additional request: Could you be more specific? Maybe give me some example of input text which causes the Traceback. 
Thank you!

**Comment by larryrodrigues** [comment]
Sorry. I meant to type more, but my session crashed.  Essentially, running any address where host is an IP, but the url ends with an extension, causes the TLD test to fail. For example http://1.2.3.4/struts_action.do  . The tld matcher thinks that ".do" is the tld, and that is not a valid ip4TLD, so the IPv4 host test is skipped.  Also, it may be worthwhile to wrap the "host.split" in an exception handler for graceful exit.

**Comment by zsavvas** [comment]
Same issue here. Downgrading to v0.13 seems to solve the issue

**Comment by jayvdb** [comment]
Also encountered this in `_is_domain_valid(url='http://172.17.23.152:8080/kom/kom/userLogin/loginall.do', tld='.do')` at

```py
> host_parts = host.split('.')
E       AttributeError: 'IPv4Address' object has no attribute 'split'
```

**Comment by lipoja** [comment]
Thanks for the reports, bug should be fixed in next release.
