### ISSUE TITLE
[bug] get wrong TLD, result in parse failed with("xxx.edu.cn@1.1.1.1")

### ISSUE THREAD

**Issue by Phantomdft** [lipoja/URLExtract#64]
First,the Traceback  is
a=extractor.find_urls("http://www.test.edu.cn@8.8.8.8:51733/hn35/")
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Python\Python36\lib\site-packages\urlextract\urlextract_core.py", line 683, in find_urls
    urls = OrderedDict.fromkeys(urls) if only_unique else urls
  File "C:\Python\Python36\lib\site-packages\urlextract\urlextract_core.py", line 645, in gen_urls
    if tld_pos != -1 and validated:
  File "C:\Python\Python36\lib\site-packages\urlextract\urlextract_core.py", line 413, in _complete_url
    complete_url, tld_pos-start_pos, tld)
  File "C:\Python\Python36\lib\site-packages\urlextract\urlextract_core.py", line 530, in _is_domain_valid
AttributeError: 'IPv4Address' object has no attribute 'split'
```
My attempt to fix this bug is in urlextract_core.py line 104:

```
        after_tld_chars = set(string.whitespace)
        after_tld_chars |= {'/', '\"', '\'', '<', '>', '?', ':', '.', ','}
        # after_tld_chars |= {'/', '\"', '\'', '<', '>', '?', ':', ','}
        # get left enclosure characters
```
I remove "." from  ater_tld_chars,and follows is my oppions:

when I trace in the urlextract_core,I find the tld  you search  is the end of domain.(For exmple
the "a.edu.cn " 'tld is cn  whether it 's edu.cn in tldextract.)
If i understand correctly, when you get tld from "test.com.cn" you should  take "cn" as tld ,but it's "com" in fact .In given case ,the url's tld will be "edu",but in fact  it's an IPV4.
So whether remove "." from  after_tld_chars will work ？Or there is any better way to solve this question.
thx

**Comment by lipoja** [comment]
Hi, thank you for reporting this issue. I really appreciate your time doing it.
I assume that it is similar to #57 which is already fixed in master branch. 

The code that is in master would return:
```python
a=extractor.find_urls("http://www.test.edu.cn@8.8.8.8:51733/hn35/")
print(a) # "[http://www.test.edu.cn@8.8.8.8:51733/hn35/]"  <- this is valid URL
```

**Comment by Phantomdft** [comment]
Ok.I got it

**Comment by Phantomdft** [comment]
print(a) # "[http://www.test.edu.cn@8.8.8.8:51733/hn35/]"  <- this is valid URL

And this is not a valid URL,the host before "@" is actually  auth part of url（scheme:[//authority]path[?query][#fragment]).This host is uint(a) # "[http://www.test.edu.cn@8.8.8.8:51733/hn35/]"  <- this is valid URL

And this is not a valid URL,the host before "@" is actually  auth part of url（scheme:[//authority]path[?query][#fragment]).This host is usually used for url derect cheating

**Comment by lipoja** [comment]
I agree that that the part before @ is used for authentication. But there is nothing invalid on that URL according to RFC. Therefore I've wrote that it is valid URL. And yes I agree, these kind of URL are usually used for phishing or other kind of web threat.
