### ISSUE TITLE
Not found ULR (stop char missing)

### ISSUE THREAD

**Issue by oxozle** [lipoja/URLExtract#66]
If there is no valid left stop char and there is no space in string valid url not found.
Example string:
`スマホの方はこちらをクリック➡https://line.me/R/ti/p/%40pnd3781y`

**Comment by lipoja** [comment]
Thank you for your time and reporting this issue. I really appreciate it. 
I am thinking about it and I am not sure how to solve it. Do you have any suggestion?

This library is not able to cover all possibilities. I am trying to make compromise in a lot of thinks which are set as default. However I am always thinking about usability and therefore I it has methods such as `set_stop_chars_left()`. I know that every text (page) is different and user should know what text is parsing and what to expect. This library should provide you all necessary functions/methods to tune it to fit users needs.

**Comment by lipoja** [comment]
@oxozle Is it OK for you to use internal methods to set your own stop characters based on the page you are parsing?
I still did not came up with any general solution.

**Comment by lipoja** [comment]
@oxozle I do not have any reply for 2 months. I am closing this issue since I think method `set_stop_chars_left()` can be used  to solve this issue.

Feel free to reopen it any time.
