### ISSUE TITLE
Considering that a url could contain "@"

### ISSUE THREAD

**Issue by eon01** [lipoja/URLExtract#7]
Hi, 

Are you using a regex for URLs extraction ?

```
python
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> from urlextract import URLExtract

>>> extractor = URLExtract()

>>> urls = extractor.find_urls("https://medium.com/@eon01/docker-rancher-efs-glusterfs-minikube-sns-sqs-microservices-and-containerd-b4c5c9c7cc0c")

>>> print(urls)
['https://medium.com']

```

**Comment by lipoja** [comment]
Hi,
no, I am not using regexp for URL extraction. But '@' is in my list of "stop characters". 
I think that I will change it a bit and I will create two lists of "stop characters" one with chars before and one after TLD. 

Thank you for reporting this issue.

**Comment by lipoja** [comment]
Default settings in version 0.7 should now return URLs containing '@' correctly.
