### ISSUE TITLE
Indexes of found URLs

### ISSUE THREAD

**Issue by javad94** [lipoja/URLExtract#71]
Any plan to include indexes of found URLs?
Something like:
input: `"Let's have URL example.com"`
output: `[('example.com', (15, 26))]`

**Comment by BenoitTS** [comment]
+1
That would be very useful so as to filter out URLs from input string.

**Comment by lipoja** [comment]
Thanks @BenoitTS for implementation. It will be part of next release.

**Comment by javad94** [comment]
Thanks @BenoitTS, really appreciate it.
