### ISSUE TITLE
Parenthesis in found urls

### ISSUE THREAD

**Issue by javad94** [lipoja/URLExtract#77]
Hi, there is a bug in the case of URLs  that ending with a slash and a parenthesis. So, for example, when we have a string such as:
`some_str = "some string with urls (example.com)"`
or
`some_str = "some string with urls ( example.com)"`
The result would be:
`['example.com']`
Which is correct. But when we have a string such as:
`some_str = "some string with urls ( example.com/somepath)"`
The result would be:
`['example.com/somepath)']`
or
`some_str = "some string with urls ( example.com/)"`
The result would be:
`['example.com/)']`
Which is inccorect.

**Comment by lipoja** [comment]
Hi @javad94,
thank you for reporting this issue.

**Comment by lipoja** [comment]
This issue will be fixed in next release.
