### ISSUE TITLE
//www.google.com cannot find such type of links 

### ISSUE THREAD

**Issue by akshayanandraut** [lipoja/URLExtract#94]

**Comment by akshayanandraut** [comment]
trying to fetch all URLs from a html response  and some scripts.src have values like <script src="//www.google.com/somejsfile.js">

These type of links are not identified

In the html world, this format is quite common and is accepted. 

I'm not sure if pre-processing the entire response to fix these links to a format identified by the urlextract lib is something I would do since that would mean that I parse through the entire response first correcting link formats and then use the find method which does the same. That would impact the performance on what I am doing. 

Let's work on this as many on stackoverflow face similar issues when links start with a character before '//'

**Comment by lipoja** [comment]
@akshayanandraut Thank you for reporting this issue. 
It should be fixed in next release (probably this week).

**Comment by akshayanandraut** [comment]
Great
Thanks man
