### ISSUE TITLE
dont url 

### ISSUE THREAD

**Issue by NeilRiver** [lipoja/URLExtract#97]
https://sportgyms.ru/

<a href="/index.php?do=feedback">Обратная связь</a>

is not 
pls fix

**Comment by NeilRiver** [comment]
`<a href="/index.php?do=feedback">Обратная связь</a>`

**Comment by lipoja** [comment]
> `<a href="/index.php?do=feedback">Обратная связь</a>`

I can not support this. Because the example above is not URL. It is HTML anchor (link). Which can me extracted from HTML site by BeautifullSoup or any other XML parser.
